import { ethers } from "ethers";
import * as dotenv from "dotenv";
dotenv.config();

// ABI fragments (minimal — full ABIs generated by Hardhat)
const FACTORY_ABI = [
  "function getAllProductIds() view returns (string[])",
  "function getProduct(string productId) view returns (tuple(address token, address vault, string productId, string strategyType, uint256 deployedAt, bool active))",
  "function deployProduct(tuple(string name, string symbol, string productId, string strategyType, uint256 redemptionDelay, uint256 minSubscription, uint256 managementFeeBps, address feeRecipient, address spvAddress) config, address vaultOperator) returns (address, address)",
];

const NAV_ORACLE_ABI = [
  "function getLatestNAV(address product) view returns (tuple(uint256 nav, uint256 timestamp, bool valid))",
  "function getTWAP(address product) view returns (uint256)",
  "function isStale(address product) view returns (bool)",
  "function updateNAV(address product, uint256 newNAV)",
  "function confirmLargeDeviation(address product, uint256 newNAV)",
];

const RWA_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function nav() view returns (uint256)",
  "function totalAssets() view returns (uint256)",
  "function convertToShares(uint256 assets) view returns (uint256)",
  "function convertToAssets(uint256 shares) view returns (uint256)",
  "function productId() view returns (string)",
  "function strategyType() view returns (string)",
];

const RWA_VAULT_ABI = [
  "function subscribe(uint256 assets) returns (uint256 shares)",
  "function requestRedemption(uint256 shares) returns (uint256 requestId)",
  "function fulfillRedemption(uint256 requestId, uint256 usdtAmount)",
  "function cancelRedemption(uint256 requestId)",
  "function vaultLiquidity() view returns (uint256)",
  "function redemptionRequests(uint256) view returns (address requester, uint256 shares, uint256 requestedAt, uint256 estimatedNAV, uint8 status, uint256 fulfilledAmount)",
  "function getPendingRedemptions(address user) view returns (uint256[], tuple(address,uint256,uint256,uint256,uint8,uint256)[])",
  "function minSubscription() view returns (uint256)",
  "function redemptionDelay() view returns (uint256)",
  "event RedemptionRequested(uint256 indexed requestId, address indexed user, uint256 shares, uint256 estimatedNAV)",
];

export function getProvider(): ethers.JsonRpcProvider {
  const rpc = process.env.RPC_URL || "http://127.0.0.1:8545";
  return new ethers.JsonRpcProvider(rpc);
}

export function getWallet(provider: ethers.JsonRpcProvider): ethers.Wallet {
  const pk = process.env.OPERATOR_PRIVATE_KEY;
  if (!pk) throw new Error("OPERATOR_PRIVATE_KEY not set");
  return new ethers.Wallet(pk, provider);
}

export async function getContracts(signerOrProvider: ethers.Signer | ethers.Provider) {
  const factoryAddr = process.env.FACTORY_ADDRESS;
  const oracleAddr  = process.env.NAV_ORACLE_ADDRESS;

  if (!factoryAddr) throw new Error("FACTORY_ADDRESS not set");
  if (!oracleAddr)  throw new Error("NAV_ORACLE_ADDRESS not set");

  return {
    factory:   new ethers.Contract(factoryAddr, FACTORY_ABI, signerOrProvider),
    navOracle: new ethers.Contract(oracleAddr,  NAV_ORACLE_ABI, signerOrProvider),
  };
}

export function getVaultContract(address: string, signer: ethers.Signer) {
  return new ethers.Contract(address, RWA_VAULT_ABI, signer);
}

export function getTokenContract(address: string, provider: ethers.Provider) {
  return new ethers.Contract(address, RWA_TOKEN_ABI, provider);
}

export { FACTORY_ABI, NAV_ORACLE_ABI, RWA_TOKEN_ABI, RWA_VAULT_ABI };
